//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Sql.Employee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Employee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Sql.Employee.Employee", typeof(Employee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Employees&quot;.
        /// </summary>
        internal static string GetAllEmployees {
            get {
                return ResourceManager.GetString("GetAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Employees&quot;
        ///where &quot;Id&quot; = any (@ids).
        /// </summary>
        internal static string GetEmployeeByIds {
            get {
                return ResourceManager.GetString("GetEmployeeByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Employees&quot;
        ///where &quot;EmployeeType&quot; = @employeeType.
        /// </summary>
        internal static string GetEmployeesByType {
            get {
                return ResourceManager.GetString("GetEmployeesByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;Employees&quot; (&quot;Id&quot;, &quot;Name&quot;, &quot;EmployeeType&quot;)
        ///values (default, @Name, @EmployeeType) {0}&quot;Id&quot;, &quot;Name&quot;, &quot;EmployeeType&quot;.
        /// </summary>
        internal static string InsertEmployee {
            get {
                return ResourceManager.GetString("InsertEmployee", resourceCulture);
            }
        }
    }
}
