//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Sql.Order {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Sql.Order.SqlOrder", typeof(SqlOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Orders&quot;.
        /// </summary>
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Tables&quot;.
        /// </summary>
        internal static string GetAllTables {
            get {
                return ResourceManager.GetString("GetAllTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Tables&quot;
        ///where &quot;Available&quot; = true.
        /// </summary>
        internal static string GetAvailibleTablesForOrder {
            get {
                return ResourceManager.GetString("GetAvailibleTablesForOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;CookingDishes&quot;
        ///where &quot;OrderId&quot; = @orderId.
        /// </summary>
        internal static string GetCookingForOrderDishesByOrder {
            get {
                return ResourceManager.GetString("GetCookingForOrderDishesByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;CookingDrinks&quot;
        ///where &quot;OrderId&quot; = @orderId.
        /// </summary>
        internal static string GetCookingForOrderDrinksByOrder {
            get {
                return ResourceManager.GetString("GetCookingForOrderDrinksByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Orders&quot;
        ///where &quot;TableNumber&quot; = @TableNumber.
        /// </summary>
        internal static string GetOrdersByTable {
            get {
                return ResourceManager.GetString("GetOrdersByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;CookingDrinks&quot; (&quot;Id&quot;, &quot;DrinkId&quot;, &quot;OrderId&quot;, &quot;StartTime&quot;, &quot;EndTime&quot;)
        ///VALUES (default,
        ///        @Id,
        ///        @DrinkId,
        ///        @OrderId,
        ///        @StartTime,
        ///        @EndTime).
        /// </summary>
        internal static string InsertCookingForDrink {
            get {
                return ResourceManager.GetString("InsertCookingForDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;CookingDishes&quot; (&quot;Id&quot;, &quot;DishId&quot;, &quot;OrderId&quot;, &quot;StartTime&quot;, &quot;EndTime&quot;)
        ///VALUES (default, @DishId, @OrderId, @StartTime, @EndTime) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertCookingForOrderDish {
            get {
                return ResourceManager.GetString("InsertCookingForOrderDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InsertOrder {
            get {
                return ResourceManager.GetString("InsertOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;ProductCookingDish&quot; (&quot;Id&quot;,
        ///                                  &quot;CookingDishId&quot;,
        ///                                  &quot;ProductId&quot;,
        ///                                  &quot;StartTime&quot;,
        ///                                  &quot;EndTime&quot;)
        ///values (default,
        ///        @CookingDishId,
        ///        @ProductId,
        ///        @StartTime,
        ///        @EndTime) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertProductCookingForOrderDish {
            get {
                return ResourceManager.GetString("InsertProductCookingForOrderDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;ProductCookingDrink&quot;
        ///(&quot;Id&quot;,
        /// &quot;CookingDrinkId&quot;,
        /// &quot;ProductId&quot;,
        /// &quot;StartTime&quot;,
        /// &quot;EndTime&quot;)
        ///values (default,
        ///        @CookingDrinkId,
        ///        @ProductId,
        ///        @StartTime,
        ///        @EndTime) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertProductCookingForOrderDrink {
            get {
                return ResourceManager.GetString("InsertProductCookingForOrderDrink", resourceCulture);
            }
        }
    }
}
