//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Sql.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Dishes&quot;.
        /// </summary>
        internal static string GetAllDishes {
            get {
                return ResourceManager.GetString("GetAllDishes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Drinks&quot;.
        /// </summary>
        internal static string GetAllDrinks {
            get {
                return ResourceManager.GetString("GetAllDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Employees&quot;.
        /// </summary>
        internal static string GetAllEmployees {
            get {
                return ResourceManager.GetString("GetAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Orders&quot;.
        /// </summary>
        internal static string GetAllOrders {
            get {
                return ResourceManager.GetString("GetAllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Tables&quot;.
        /// </summary>
        internal static string GetAllTables {
            get {
                return ResourceManager.GetString("GetAllTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Tables&quot;
        ///where &quot;Available&quot; = true.
        /// </summary>
        internal static string GetAvailibleTables {
            get {
                return ResourceManager.GetString("GetAvailibleTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;CookingDishes&quot;
        ///where &quot;OrderId&quot; = @orderId.
        /// </summary>
        internal static string GetCookingDishesByOrder {
            get {
                return ResourceManager.GetString("GetCookingDishesByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;CookingDrinks&quot;
        ///where &quot;OrderId&quot; = @orderId.
        /// </summary>
        internal static string GetCookingDrinksByOrder {
            get {
                return ResourceManager.GetString("GetCookingDrinksByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Dishes&quot;
        ///where &quot;Id&quot; = @id.
        /// </summary>
        internal static string GetDishById {
            get {
                return ResourceManager.GetString("GetDishById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Dishes&quot;
        ///where &quot;Id&quot; in @ids.
        /// </summary>
        internal static string GetDishByIds {
            get {
                return ResourceManager.GetString("GetDishByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Dishes&quot;
        ///where &quot;DishType&quot; = @DishType.
        /// </summary>
        internal static string GetDishByType {
            get {
                return ResourceManager.GetString("GetDishByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Drinks&quot;
        ///where &quot;Id&quot; = @id.
        /// </summary>
        internal static string GetDrinkById {
            get {
                return ResourceManager.GetString("GetDrinkById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Drinks&quot;
        ///where &quot;DrinkType&quot; = @DrinkType.
        /// </summary>
        internal static string GetDrinkByType {
            get {
                return ResourceManager.GetString("GetDrinkByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Employees&quot;
        ///where &quot;Id&quot; = @id.
        /// </summary>
        internal static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Employees&quot;
        ///where &quot;Id&quot; in @ids.
        /// </summary>
        internal static string GetEmployeesByIds {
            get {
                return ResourceManager.GetString("GetEmployeesByIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Orders&quot;
        ///where &quot;TableNumber&quot; = @TableNumber.
        /// </summary>
        internal static string GetOrdersByTable {
            get {
                return ResourceManager.GetString("GetOrdersByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;ProductDish&quot;
        ///where &quot;DishId&quot; = @dishId
        ///.
        /// </summary>
        internal static string GetProductDishByDish {
            get {
                return ResourceManager.GetString("GetProductDishByDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select *
        ///from &quot;Employees&quot;.
        /// </summary>
        internal static string GetProductDrinkByDrink {
            get {
                return ResourceManager.GetString("GetProductDrinkByDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;CookingDishes&quot; (&quot;Id&quot;, &quot;DishId&quot;, &quot;OrderId&quot;, &quot;StartTime&quot;, &quot;EndTime&quot;)
        ///VALUES (default, @DishId, @OrderId, @StartTime, @EndTime) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertCookingDish {
            get {
                return ResourceManager.GetString("InsertCookingDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;CookingDrinks&quot; (&quot;Id&quot;, &quot;DrinkId&quot;, &quot;OrderId&quot;, &quot;StartTime&quot;, &quot;EndTime&quot;)
        ///VALUES (default,
        ///        @Id,
        ///        @DrinkId,
        ///        @OrderId,
        ///        @StartTime,
        ///        @EndTime).
        /// </summary>
        internal static string InsertCookingDrink {
            get {
                return ResourceManager.GetString("InsertCookingDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;Drinks&quot; (&quot;Id&quot;,
        ///                      &quot;Name&quot;,
        ///                      &quot;DrinkType&quot;,
        ///                      &quot;Cost&quot;)
        ///values (default,
        ///        @Name,
        ///        @DrinkType,
        ///        @Cost) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertDish {
            get {
                return ResourceManager.GetString("InsertDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;Employees&quot; (&quot;Id&quot;, &quot;Name&quot;, &quot;EmployeeType&quot;, &quot;EmployeeRang&quot;)
        ///values (default, @Name, @EmployeeType, @EmployeeRang) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertEmployee {
            get {
                return ResourceManager.GetString("InsertEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InsertOrder {
            get {
                return ResourceManager.GetString("InsertOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InsertProduct {
            get {
                return ResourceManager.GetString("InsertProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;ProductCookingDish&quot; (&quot;Id&quot;,
        ///                                  &quot;CookingDishId&quot;,
        ///                                  &quot;ProductId&quot;,
        ///                                  &quot;StartTime&quot;,
        ///                                  &quot;EndTime&quot;)
        ///values (default,
        ///        @CookingDishId,
        ///        @ProductId,
        ///        @StartTime,
        ///        @EndTime) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertProductCookingDish {
            get {
                return ResourceManager.GetString("InsertProductCookingDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into &quot;ProductCookingDrink&quot;
        ///(&quot;Id&quot;,
        /// &quot;CookingDrinkId&quot;,
        /// &quot;ProductId&quot;,
        /// &quot;StartTime&quot;,
        /// &quot;EndTime&quot;)
        ///values (default,
        ///        @CookingDrinkId,
        ///        @ProductId,
        ///        @StartTime,
        ///        @EndTime) {0}&quot;Id&quot;.
        /// </summary>
        internal static string InsertProductCookingDrink {
            get {
                return ResourceManager.GetString("InsertProductCookingDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        /// // &lt;auto-generated&gt;
        /// //     This code was generated by a tool.
        /// //
        /// //     Changes to this file may cause incorrect behavior and will be lost if
        /// //     the code is regenerated.
        /// // &lt;/auto-generated&gt;
        /// //------------------------------------------------------------------------------
        ///
        ///namespace DataAccess.Sql {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-typed resource class, for looking up localized [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql_Designer {
            get {
                return ResourceManager.GetString("Sql_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlRes {
            get {
                return ResourceManager.GetString("SqlRes", resourceCulture);
            }
        }
    }
}
